build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Paulo Cavalcante - Developer"
    email: "educavalcantedev@gmail.com"
  onCallSupport:
    - (555) 555-1234