build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related PROD APIs"
  contactDetails:
    name: "Chris Adam - Product Owner"
    email: "chrisadam@gmail.com"
  onCallSupport:
    - (777) 777-1234